# Generated by Django 5.2 on 2025-05-04 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiel',
            name='categorie',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='materiels.categoriemateriel'),
        ),
    ]
