# Generated by Django 5.2 on 2025-04-13 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_phone_number_user_profile_picture_and_more'),
        ('organisation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='unite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organisation.unite'),
        ),
    ]
