# Generated by Django 5.2 on 2025-04-15 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_unite'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='doit_changer_mot_de_passe',
            field=models.BooleanField(default=True),
        ),
    ]
