# Generated by Django 5.2 on 2025-05-04 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiels', '0002_alter_materiel_categorie'),
        ('pannes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='panne',
            name='categorie_materiel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pannes', to='materiels.categoriemateriel'),
        ),
        migrations.AddField(
            model_name='panne',
            name='materiel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pannes', to='materiels.materiel'),
        ),
        migrations.AlterField(
            model_name='affectationpanne',
            name='attribue_par',
            field=models.ForeignKey(limit_choices_to={'role__name': 'chef unite informatique'}, on_delete=django.db.models.deletion.CASCADE, related_name='panne_attribue_par', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='affectationpanne',
            name='technicien',
            field=models.ForeignKey(limit_choices_to={'role__name': 'technicien'}, on_delete=django.db.models.deletion.CASCADE, related_name='panne_technicien', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='panne',
            name='user',
            field=models.ForeignKey(limit_choices_to={'role__name': 'utilisateur'}, on_delete=django.db.models.deletion.CASCADE, related_name='panne_utilisateur', to=settings.AUTH_USER_MODEL),
        ),
    ]
