# Generated by Django 5.2 on 2025-05-20 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pannes', '0002_panne_categorie_materiel_panne_materiel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='panne',
            name='titre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
