# Generated by Django 5.2 on 2025-06-22 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pannes', '0003_panne_titre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panne',
            name='status',
        ),
        migrations.AlterField(
            model_name='affectationpanne',
            name='statut_reparation',
            field=models.CharField(choices=[('non_traitee', 'Non traitée'), ('en_cours', 'En cours'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='non_traitee', max_length=20),
        ),
    ]
