# Generated by Django 5.2 on 2025-06-23 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pannes', '0004_remove_panne_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='affectationpanne',
            name='date_reparation',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
