# Generated by Django 5.2 on 2025-06-23 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pannes', '0005_affectationpanne_date_reparation'),
    ]

    operations = [
        migrations.AddField(
            model_name='affectationpanne',
            name='commentaire_intervention',
            field=models.TextField(blank=True, null=True),
        ),
    ]
